web:
  restart: always
  env_file:
    - .env
  image: vanessa/som-api
  expose:
    - "5000"
  volumes:
    - /usr/src/app/static
    - .:/code
  command: /usr/local/bin/gunicorn -w 2 -b :5000 app.main:app

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    - /etc/ssl/certs:/etc/ssl/certs:ro
    - /etc/ssl/private:/etc/ssl/private:ro
  volumes_from:
    - web
  links:
    - web:web

